Console.WriteLine("Введите значение x:");
int x = Convert.ToInt32(Console.ReadLine());
var exercise1 = -6 + x * 5;
var exercise2 = (13-2) * x;
var exercise3 = (x + -2) * (20 / 10);
var exercise4 = (12 + x) / (5 - 4);
Console.WriteLine(exercise1);
Console.WriteLine(exercise2);
Console.WriteLine(exercise3);
Console.WriteLine(exercise4);