Console.WriteLine("Введите значение a:");
decimal a = Convert.ToDecimal(Console.ReadLine());
Console.WriteLine("Введите значение b:");
decimal b = Convert.ToDecimal(Console.ReadLine());
Console.WriteLine("Введите значение c:");
decimal c = Convert.ToDecimal(Console.ReadLine());
var result1 = (a + b) * c;
var result2 = a * c + b * c;
Console.WriteLine(result1);
Console.WriteLine(result2);